"""add deleted column for client, remove has_unfinished_choices

Revision ID: 64c629922971
Revises: 8a7bbfd21037
Create Date: 2024-07-12 02:05:50.674145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64c629922971'
down_revision: Union[str, None] = '8a7bbfd21037'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('client', sa.Column('deleted', sa.Boolean(), nullable=True))
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_column('has_unfinished_choices')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('has_unfinished_choices', sa.BOOLEAN(), nullable=True))
    with op.batch_alter_table('client', schema=None) as batch_op:
       batch_op.drop_column('deleted')
